<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
	<array>
		<string>cgfx</string>
		<string>cgh</string>
		<string>cg</string>
		<string>fx</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>CgFX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(break|case|continue|default|discard|do|else|for|if|return|switch|while|try|catch|goto|throw)\b</string>
			<key>name</key>
			<string>keyword.control.glsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((void|bool|int|char|float|double|half|long|short|signed|unsigned|fixed)([2-4]|([2-4]x[2-4]))?|sampler(1D|2D|3D|_state|CUBE)?|texture(1D|2D|3D|CUBE|RECT))\b</string>
			<key>name</key>
			<string>storage.type.glsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(const|extern|in|inline|inout|static|out|uniform|varying|packed)\b</string>
			<key>name</key>
			<string>storage.modifier.glsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b()\b</string>
			<key>name</key>
			<string>support.variable.glsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(gl_MaxClipPlanes|gl_MaxCombinedTextureImageUnits|gl_MaxDrawBuffers|gl_MaxFragmentUniformComponents|gl_MaxLights|gl_MaxTextureCoords|gl_MaxTextureImageUnits|gl_MaxTextureUnits|gl_MaxVaryingFloats|gl_MaxVertexAttribs|gl_MaxVertexTextureImageUnits|gl_MaxVertexUniformComponents)\b</string>
			<key>name</key>
			<string>support.constant.glsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abs|acos|all|any|asin|atan|ceil|clamp|cos|cross|degrees|dFdx|dFdy|distance|dot|equal|exp|exp2|faceforward|floor|fract|ftransform|fwidth|greaterThan|greaterThanEqual|inversesqrt|length|lessThan|lessThanEqual|log|log2|matrixCompMult|max|min|mix|mod|noise[1-4]|normalize|not|notEqual|outerProduct|pow|radians|reflect|refract|shadow1D|shadow1DLod|shadow1DProj|shadow1DProjLod|shadow2D|shadow2DLod|shadow2DProj|shadow2DProjLod|sign|sin|smoothstep|sqrt|step|tan|texture1D|texture1DLod|texture1DProj|texture1DProjLod|texture2D|texture2DLod|texture2DProj|texture2DProjLod|texture3D|texture3DLod|texture3DProj|texture3DProjLod|textureCube|textureCubeLod|transpose)\b</string>
			<key>name</key>
			<string>support.function.glsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+(\.\d+)?([dfhilstux]|u[stil]))\b</string>
			<key>name</key>
			<string>constant.numeric.glsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(asm|double|enum|extern|goto|inline|long|short|sizeof|static|typedef|union|unsigned|volatile)\b</string>
			<key>name</key>
			<string>invalid.illegal.glsl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.glsl</string>
	<key>uuid</key>
	<string>D0FD1B52-F137-4FBA-A148-B8A893CD948C</string>
</dict>
</plist>
